### ISSUE TITLE
nie działa

### ISSUE THREAD

**Issue by Proallone** [amadeuszdrabiniok/BMICalculator#1]
nie działa`
- [ nie działa ] 
- [

**Comment by amadeuszdrabiniok** [comment]
Sorry to hear that :( , but im sure you are doing something wrong. Can you describe your problem?

**Comment by Proallone** [comment]
- [ ] 

1. thanks for answer

**Comment by Proallone** [comment]
![logo_pwr](https://user-images.githubusercontent.com/46166114/137709734-904cefc5-75ae-49d7-91e5-4d982cc426c1.jpg)
